### ISSUE TITLE
Create Deployment objects for Jars to auto-deploy to k8s

### ISSUE THREAD

**Issue by devinbost** [datastax/pulsar_workshop#18]
We can template creation of Deployment objects in k8s that wrap execution of our Jar files so that we can deploy them into k8s. (This will also help us to test/eval cases when we need to scale a producer or consumer horizontally.)

We could use something like this (though I'm sure there's a better way to handle the token):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pulsar-load-producer
  name: pulsar-load-producer
  namespace: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar-load-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pulsar-load-producer
    spec:
      containers:
      - image: devingbost/pulsar-demos:regex-v16
        name: load-producer
        command: ["java"]
        args:  ["-jar", "/opt/app/load-demo-0.0.1-jar-with-dependencies.jar", "--usage", "produce", "--topic-base", "$(TOPIC)", "--subscription-name","$(SUBSCRIPTION)", "--service-url", "$(SERVICE_URL)", "--token", "ey...g"]
        volumeMounts:
          - mountPath: /pulsar/token-superuser
            name: token-superuser
            readOnly: true
        env:
        - name: SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: pulsar-load-test-configs
              key: serviceUrl
        - name: TOPIC
          valueFrom:
            configMapKeyRef:
              name: pulsar-load-test-configs
              key: topicBase
        - name: SUB_TYPE
          valueFrom:
            configMapKeyRef:
              name: pulsar-load-test-configs
              key: subscriptionType
        - name: SUB_POS
          valueFrom:
            configMapKeyRef:
              name: pulsar-load-test-configs
              key: subscriptionPosition
        - name: SUBSCRIPTION
          valueFrom:
            configMapKeyRef:
              name: pulsar-load-test-configs
              key: subscription
        - name: AUTH_PLUGIN
          valueFrom:
            configMapKeyRef:
              name: pulsar-load-test-configs
              key: authPlugin
        - name: AUTH_PARAMS
          valueFrom:
            configMapKeyRef:
              name: pulsar-load-test-configs
              key: authParams
        resources: {}
      volumes:
      - name: token-superuser
        secret:
          defaultMode: 420
          secretName: token-superuser
status: {}
```

To actually run that, we also need automation for building the Docker image for each Jar. The docker images that we generate could look something like this:

```
FROM eclipse-temurin:11
RUN mkdir /opt/app
COPY java/load-demo/target/load-demo-0.0.1-jar-with-dependencies.jar /opt/app

CMD ["java", "-jar", "/opt/app/load-demo-0.0.1-jar-with-dependencies.jar", "--topic-base", "persistent://public/default/testme", "--subscription-name","example-sub", "--service-url", "pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650", "--token", "ey...0g"]
```
(although I'm sure there's a better way to handle the token here too.)

And, then we'd need to run the commands for `docker build` (or buildx if on M1) and then to push to an image hub. 

-----

With this said, it raises the question of at what point we should be using an Operator for a CI/CD framework, like Tekton, instead of doing everything in bash.
